### PR TITLE
Add stream support to gulp-filenames

### PR DESCRIPTION
**Pull request by bmacnaughton**
I added stream support and a test that it works.

Minor cleanup of package.json.

I also added myself to package.json as a contributor - I hope you are OK with that.

### CODE REVIEW

**Comment by JohnyDays** [comment]
Thanks @bmacnaughton! Do you regularly use this package?
PS: Published as 3.0.0

**Comment by bmacnaughton** [comment]
I use it in our gulp system that packages a framework for designers and also packages their designs, the framework, and integrates them into our website (not published yet). So I use it on a regular basis but not in many projects. I use it so that it is easy to create both development releases for debugging and testing (files are not concatenated and minimized) and production releases (files are concatenated and minimized). I collect the filenames with JavaScript gulp tasks then insert `<script>` tags into pages and/or PHP code that generates pages using the collected filenames.

I've never seen it error because of streams but I created a really generic replacement plugin (gulp-markers) and got familiar with streams because I needed to concatenate them to do RE matching. When I saw issue #5 I made a note to test my streams knowledge and update the gulp-filenames.

**Comment by JohnyDays** [comment]
Thanks for the in-depth explanation. I ask because I haven't used gulp in quite a while (currently using webpack), and I'd be willing to give you control of the repository/npm package if you need to do any further development. 
Although I believe that the package doesn't really need any more development, since it has such a small scope. Cheers

**Comment by bmacnaughton** [comment]
If you'd like to give me write access I'd be happy to contribute without having to request pulls from you. Or if you'd like to give me control of the repo/npm I"d take that as well (presuming you'd still have write access). This has forced me to learn some coffeescript, so it's been interesting in more than one way.

**Pull request merged**
